name: my-better-t-app

services:
  web:
    build:
      context: .
    ports:
      - "3001:3001"
    command: >
      sh -c "pnpm --filter @my-better-t-app/db db:push && pnpm --filter web dev"

    depends_on:
      postgres:
        condition: service_healthy
    volumes: 
      - ./apps/web/public/uploads:/apps/web/public/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/my-better-t-app
      - BETTER_AUTH_SECRET=etihbDoDbmmxzb96cdn99ZbZHEMBX6jb
      - BETTER_AUTH_URL=http://localhost:3001
      - CORS_ORIGIN=http://localhost:3001
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: my-better-t-app-postgres
    environment:
      POSTGRES_DB: my-better-t-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - my-better-t-app_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  my-better-t-app_postgres_data: