/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as IncidentsCreateRouteImport } from './routes/incidents/create'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents/$incidentId'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiIncidentsUploadRouteImport } from './routes/api/incidents/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsCreateRoute = IncidentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => IncidentsRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsUploadRoute = ApiIncidentsUploadRouteImport.update({
  id: '/api/incidents/upload',
  path: '/api/incidents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/create': typeof IncidentsCreateRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/incidents/upload': typeof ApiIncidentsUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/create': typeof IncidentsCreateRoute
  '/incidents': typeof IncidentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/incidents/upload': typeof ApiIncidentsUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/create': typeof IncidentsCreateRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/incidents/upload': typeof ApiIncidentsUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/incidents'
    | '/login'
    | '/incidents/$incidentId'
    | '/incidents/create'
    | '/incidents/'
    | '/api/auth/$'
    | '/api/incidents/upload'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/incidents/$incidentId'
    | '/incidents/create'
    | '/incidents'
    | '/api/auth/$'
    | '/api/incidents/upload'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/incidents'
    | '/login'
    | '/incidents/$incidentId'
    | '/incidents/create'
    | '/incidents/'
    | '/api/auth/$'
    | '/api/incidents/upload'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIncidentsUploadRoute: typeof ApiIncidentsUploadRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/create': {
      id: '/incidents/create'
      path: '/create'
      fullPath: '/incidents/create'
      preLoaderRoute: typeof IncidentsCreateRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents/upload': {
      id: '/api/incidents/upload'
      path: '/api/incidents/upload'
      fullPath: '/api/incidents/upload'
      preLoaderRoute: typeof ApiIncidentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IncidentsRouteChildren {
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsCreateRoute: typeof IncidentsCreateRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsCreateRoute: IncidentsCreateRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIncidentsUploadRoute: ApiIncidentsUploadRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
